Fix builddoc with sphinx <= 1.6
I went to build infra-specs which specifies sphinx==1.5.6 and hit

 Traceback (most recent call last):
   File "setup.py", line 29, in <module>
     pbr=True)
   ...
  File ".../pbr/builddoc.py", line 235, in run
    self._sphinx_run()
  File ".../pbr/builddoc.py", line 162, in _sphinx_run
    freshenv=self.fresh_env, warningiserror=self.warning_is_error)
  File ".../sphinx/application.py", line 244, in __init__
    self._init_builder(self.buildername)
  File "...//sphinx/application.py", line 311, in _init_builder
    raise SphinxError('Builder name %s not registered' % buildername)
 sphinx.errors.SphinxError: Builder name h not registered

It appears to be a typo introduced with
I18bbf693bca2f6e49d822ae2940d2170a2b90ce9; make sure we're walking the
self.builders list; not the string self.builder.

Change-Id: Ic038029c361b3ede48f2b495c74430d3ad1eab82