Fix functional test for pip 25.3
It appears that pip applies the --no-index configuration to isolated
build environments leading to errors like this when we try to build our
test packages:

  Processing /tmp/tmpdhkm1rkk/tmpaik8vv54/repo/test_markers-0.0.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'error'
  STDERR:
  error: subprocess-exited-with-error

    Ã� installing build dependencies for test_markers did not run successfully.
    â�� exit code: 1
    â�°â��> [3 lines of output]
        Looking in links: /tmp/tmpdhkm1rkk/tmpaik8vv54/repo
        ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0 (from versions: none)
        ERROR: No matching distribution found for setuptools>=40.8.0
        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed to build 'test_markers' when installing build dependencies for test_markers

Address this by passing --no-build-isolation to the test cases. This may
introduce additional problems but we're already running the pip install
out of a dedicated venv so they should be fairly isolated to this small
test case setup.

Change-Id: I91872688982110297a589d3cb2bec6edea37dea0
Signed-off-by: Clark Boylan <clark.boylan@gmail.com>